FROM ubuntu:18.04
MAINTAINER Alexandr Koptev, alexandr.koptev@onix-systems.com

RUN apt-get update && \
    apt-get upgrade -y

# Set the locale (I want to use German Umlauts)
#RUN locale-gen en_US.UTF-8
#ENV LANG en_US.UTF-8
#ENV LANGUAGE en_US:en
#ENV LC_ALL en_US.UTF-8

# Set the timezone (change this to your local timezone)
RUN echo "Europe/Kiev" | tee /etc/timezone
#RUN dpkg-reconfigure --frontend noninteractive tzdata

RUN apt-get install -y \
    ssmtp \
    cron \
    mysql-client \
    mpack
#    zip \
#    mpack
#    zip
#    msmtp \
#    mutt \
#    vim
ADD ssmtp.conf /etc/ssmtp/ssmtp.conf
# Add crontab file in the cron directory
ADD sqldump_mailsend.sh /root
ADD crontab /etc/cron.d/hello-cron
# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/hello-cron
# Apply cron job
RUN crontab /etc/cron.d/hello-cron
# Create the log file to be able to run tail
RUN touch /var/log/cron.log
# Run the command on container startup
CMD cron && tail -f /var/log/cron.log
# RUN adduser --disabled-login --gecos '' mutt
#RUN mkdir root
WORKDIR /root
#USER mutt

#ENTRYPOINT /bin/bash -c 'if [ -f ~/.muttrc -a -f ~/.msmtprc ] ; then /usr/bin/mutt ; else echo "ERROR: /home/mutt/.muttrc or /home/mutt/.msmtprc not found." ; fi'
